"""add payment_method to bookings

Revision ID: 8487101d0b45
Revises: 16a3c0bc43d8
Create Date: 2026-07-18 15:52:01.015649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8487101d0b45'
down_revision: Union[str, None] = '16a3c0bc43d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method_enum = sa.Enum('CASH', 'DEMO_ONLINE', name='paymentmethod')
    payment_method_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'bookings',
        sa.Column(
            'payment_method',
            payment_method_enum,
            nullable=False,
            server_default='CASH',
        ),
    )
    # Drop the server default after backfilling - the application always
    # supplies payment_method explicitly going forward.
    op.alter_column('bookings', 'payment_method', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_method')
    sa.Enum(name='paymentmethod').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
